---
- name: set epic_firewall_short
  ansible.builtin.set_fact:
    epic_firewall_short: "{{ item['name'] }}"
  tags:
    - firewall

- name: set epic_firewall_description
  ansible.builtin.set_fact:
    epic_firewall_description: "{{ item['description'] }}"
  tags:
    - firewall

- name: set epic_firewall_ports
  ansible.builtin.set_fact:
    epic_firewall_ports: "{{ item['ports'] }}"
  tags:
    - firewall

- name: copy {{ epic_firewall_short }} firewall rule
  ansible.builtin.template:
    src: firewalld.xml.j2
    dest: /etc/firewalld/services/{{ epic_firewall_short }}.xml
    owner: root
    group: root
    mode: 0660
  tags:
    - firewall
