---

- name: Set epic_firewall_short
  ansible.builtin.set_fact:
    epic_firewall_short: "{{ firewall_service['name'] }}"
  tags:
    - firewall

- name: Set epic_firewall_description
  ansible.builtin.set_fact:
    epic_firewall_description: "{{ firewall_service['description'] }}"
  tags:
    - firewall

- name: Set epic_firewall_ports
  ansible.builtin.set_fact:
    epic_firewall_ports: "{{ firewall_service['ports'] }}"
  tags:
    - firewall

- name: Clear ufw ports line
  ansible.builtin.set_fact:
    ufw_epic_firewall_ports: ''
  tags:
    - firewall

- name: Set ufw ports line
  ansible.builtin.set_fact:
    ufw_epic_firewall_ports: "{{ ufw_epic_firewall_ports | default('') }}{{ (ansible_loop['index'] > 1) | ternary(',', '') }}{{ item['port'] }}"
  loop: "{{ epic_firewall_ports }}"
  loop_control:
    extended: true
  when: ansible_distribution == 'Ubuntu'
  tags:
    - firewall

- name: Add protocol to ufw ports line
  ansible.builtin.set_fact:
    ufw_epic_firewall_ports: "{{ ufw_epic_firewall_ports }}/{{ firewall_service['protocol'] | default('tcp') }}"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - firewall

- name: Copy firewall rule {{ epic_firewall_short }}
  ansible.builtin.template:
    src: firewalld.xml.j2
    dest: /etc/firewalld/services/{{ epic_firewall_short }}.xml
    owner: root
    group: root
    mode: "0660"
  when: ansible_distribution != 'Ubuntu'
  tags:
    - firewall

- name: Copy firewall rule {{ epic_firewall_short }}
  ansible.builtin.template:
    src: ufw_app.j2
    dest: /etc/ufw/applications.d/{{ epic_firewall_short }}
    owner: root
    group: root
    mode: "0660"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - firewall

...
