---
- name: check for {{ item['name'] }} sysctl setting
  stat:
    path: /proc/sys/{{ item['name'] | replace('.','/') }}
  register: sysctl_setting

- name: configure {{ item['name'] }} sysctl
  sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    sysctl_file: /etc/sysctl.d/99-epic.conf
    sysctl_set: true
    state: present
    reload: true
  when: sysctl_setting['stat']['exists']
