---
epic_users:
  - {user: epicadm,
     comment: "Epic Admin",
     ansible.builtin.group: epicsys,
     groups: "epicuser,cachegrp,dmngrp",
     uid: 10000,
     state: present,
     password: "{{ epic_passwords['epicadm'] }}"}
  - {user: epicdmn,
     comment: "Epic Daemon",
     ansible.builtin.group: epicuser,
     groups: dmngrp,
     uid: 10001,
     state: present,
     password: "{{ epic_passwords['epicdmn'] }}"}
  - {user: epicsupt,
     comment: "Epic Tempmlate",
     ansible.builtin.group: epicuser,
     groups: users,
     uid: 10002,
     state: present,
     password: "{{ epic_passwords['epicsupt'] }}"}
  - {user: epictxt,
     comment: "Epic Text",
     ansible.builtin.group: epicuser,
     groups: users,
     uid: 10003,
     state: present,
     password: "{{ epic_passwords['epictxt'] }}"}
  - {user: iscagent,
     comment: "Epic iscagent",
     ansible.builtin.group: epicuser,
     groups: users,
     uid: 10004,
     state: present,
     password: "{{ epic_passwords['iscagent'] }}"}
