---
on: push  # yamllint disable-line rule:truthy

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
